services:
  - type: web
    name: banking-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: URL_PROD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 1h
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_API_KEY
        sync: false
